@baseUrl = http://localhost:8080
# 每次重新登录以后更新
@accessToken = PASTE_ACCESS_TOKEN_HERE
# 每次重新登录以后更新
@refreshToken = PASTE_ACCESS_TOKEN_HERE


### ================================================
### 1. 登录
### ================================================

POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "alice",
  "password": "Alice123456"
}


### ================================================
### 2. 登录后查询当前用户
### 预期：200
### ================================================

GET {{baseUrl}}/api/users/me
Authorization: Bearer {{accessToken}}


### ================================================
### 3. Logout
### 预期：200
### ================================================

POST {{baseUrl}}/api/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### ================================================
### 4. 使用已经 Logout 的 Access Token
### 预期：401
### ================================================

GET {{baseUrl}}/api/users/me
Authorization: Bearer {{accessToken}}


### ================================================
### 5. 使用已经 Logout 的 Refresh Token
### 预期：401
### ================================================

POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}